
### Get all users
# Expected status: 200
GET http://localhost:8080/users  HTTP/1.1
    content-type: application/json


### Get user
# Expected status: 200
GET http://localhost:8080/users/1  HTTP/1.1
    content-type: application/json

### Delete user
# Expected status: 200
DELETE http://localhost:8080/users/2  HTTP/1.1
    content-type: application/json


### Create user
# Expected status: 201
POST http://localhost:8080/users  HTTP/1.1
   content-type: application/json

   {
        "name" : "Tim",
        "birthDate" : "1975-12-12"
   }

### Bad endpoint -> Status 404

POST http://localhost:8080/blah  HTTP/1.1


### Non-existing id -> Status 404

POST http://localhost:8080/users/404  HTTP/1.1
